import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  layer2Sidebar:        [{ type: 'autogenerated', dirName: '01-layer2' }],
  ospfSidebar:          [{ type: 'autogenerated', dirName: '02-ospf' }],
  eigrpSidebar:         [{ type: 'autogenerated', dirName: '03-eigrp' }],
  bgpSidebar:           [{ type: 'autogenerated', dirName: '04-bgp' }],
  routePolicySidebar:   [{ type: 'autogenerated', dirName: '05-route-policy' }],
  mplsSidebar:          [{ type: 'autogenerated', dirName: '06-mpls' }],
  sdwanSidebar:         [{ type: 'autogenerated', dirName: '07-sdwan' }],
  securitySidebar:      [{ type: 'autogenerated', dirName: '08-security' }],
  vpnSidebar:           [{ type: 'autogenerated', dirName: '09-vpn' }],
  firewallSidebar:      [{ type: 'autogenerated', dirName: '10-firewall' }],
  qosSidebar:           [{ type: 'autogenerated', dirName: '11-qos' }],
  ipServicesSidebar:    [{ type: 'autogenerated', dirName: '12-ip-services' }],
  ipv6Sidebar:          [{ type: 'autogenerated', dirName: '13-ipv6' }],
  automationSidebar:    [{ type: 'autogenerated', dirName: '14-automation' }],
  designSidebar:        [{ type: 'autogenerated', dirName: '15-design' }],
  troubleshootingSidebar: [{ type: 'autogenerated', dirName: '16-troubleshooting' }],
};

export default sidebars;
